version: '3.8'
networks:
  cpe_ctfd_dev_net:
    driver: bridge

services:
  proxy:
    container_name: proxy.$PREFIX
    image: nginx:1.21.6
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80